import { NextAuthProvider } from "./providers/NextAuthProvider";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css'
import Menu from "@/componentes/Menu";
import { Suspense } from 'react';
import Loading from '@/componentes/comuns/Loading';

export const metadata = {
  title: "eShop Next 14",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <NextAuthProvider>
          <Menu/>
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </NextAuthProvider>
      </body>
    </html>
  );
}
